.PHONY: all clean build package

all: clean build package

build:
	# Build frontend assets with Yarn
	yarn install && yarn tauri build --debug

package:
	# Create release directory structure
	mkdir -p target/debug/config
	mkdir -p target/debug/deps/config

	# Copy additional required files
	cp -r config/* target/debug/config/
	cp config_real.toml target/debug/config/gui-config.toml
	cp config_real.toml target/debug/deps/config/gui-config.toml

	
